const {Ejs_Model} = require('../../EjsModel_Class/EjsModel_Class.js')
const {MODEL_OBJECTS} = require('./artBoardModelObjects.js')

let ARTBOARDMODEL = new Ejs_Model(MODEL_OBJECTS.MODEL_OBJECT_01)

ARTBOARDMODEL.model.MODULE_CHILDREN_DATA.CHILDREN.push(MODEL_OBJECTS.MODEL_OBJECT_02)
// ARTBOARDMODEL.model.MODULE_CHILDREN_DATA.CHILDREN.push(MODEL_OBJECTS.MODEL_OBJECT_03)
// ARTBOARDMODEL.model.MODULE_CHILDREN_DATA.CHILDREN[0].MODULE_CHILDREN_DATA.CHILDREN.push(MODEL_OBJECTS.MODEL_OBJECT_04)
// ARTBOARDMODEL.model.MODULE_CHILDREN_DATA.CHILDREN[1].MODULE_CHILDREN_DATA.CHILDREN.push(MODEL_OBJECTS.MODEL_OBJECT_05)

// console.log(ARTBOARDMODEL.model.MODULE_CHILDREN_DATA)




const data = [
    MODEL_OBJECTS
  ]

console.log(data)
  
// ARTBOARDMODEL.model.MODULE_CHILDREN_DATA.CHILDREN[0].MODULE_CHILDREN_DATA.CHILDREN.push(MODEL_OBJECTS.MODEL_OBJECT_03)


// ARTBOARDMODEL.injectChildObjIntoParentObj(MODEL_OBJECTS.MODEL_OBJECT_02)

// let parent = ARTBOARDMODEL.inject(MODEL_OBJECTS.MODEL_OBJECT_02, MODEL_OBJECTS.MODEL_OBJECT_03)

// console.log("newthing")
// console.log(ARTBOARDMODEL)
// console.log("parent")
// console.log(parent)
// // console.log(child)

module.exports = {ARTBOARDMODEL}